---
# install-RedHat.yml
#

- name: Install system updates
  yum:
    name: '*'
    state: latest
    update_cache: yes
  ignore_errors: True
  when: perfsonar_os_update == True

- name: yum epel-release
  yum:
    name: epel-release
    state: latest

- name: yum repo
  yum:
    name: http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8-1.noarch.rpm
    state: present

- name: Use perfSONAR staging or nightly repository
  yum:
    name: perfSONAR-repo-{{ perfsonar_release }}
    state: present
  when:
    - perfsonar_release == "staging" or perfsonar_release == "nightly"

- name: yum clean all
  command: yum clean all

- name: perfsonar yum autoupdate
  service:
    name: yum-cron
    state: started
    enabled: yes
  when: perfsonar_autoupdate == true and ansible_os_family == "RedHat"
