---
# install-Debian.yml
#

- name: Import perfSONAR repository signing key (Debian based systems)
  apt_key:
    url: http://downloads.perfsonar.net/debian/perfsonar-debian-official.gpg.key
    state: present

- name: Add perfSONAR repository (Debian based systems)
  apt_repository:
    repo: deb http://downloads.perfsonar.net/debian/ perfsonar-jessie-release main
    state: present

- name: Install system updates (Debian based systems)
  apt:
    upgrade: dist
    update_cache: yes
  ignore_errors: True

### Autoupdate Debian
- name: download perfSONAR unattended-upgrades package
  package:
    name: unattended-upgrades
    state: latest
  when: perfsonar_autoupdate is defined and perfsonar_autoupdate == true and
        ansible_os_family == "Debian"

- name: execute perfSONAR unattended-upgrades package
  command: /usr/lib/perfsonar/scripts/system_environment/enable_auto_updates new
  when: perfsonar_autoupdate is defined and perfsonar_autoupdate == true and
        ansible_os_family == "Debian"
