---
# tasks file for ansible-role-perfsonar/

- name: Load variables based on OS type
  include_vars: "{{ item }}"
  tags: [ 'always' ]
  with_items:
    - "{{ ansible_os_family }}.yml"

- name: check to see if requested bundle is supported "{{ perfsonar_bundle }}"
  fail:
    msg: "Unsupported bundle requested"
  tags:
    - ps:install
  when: perfsonar_bundle != "perfsonar-toolkit" and
        perfsonar_bundle != "perfsonar-testpoint"

- name: RedHat Specific Install
  include_tasks: install-RedHat.yml
  tags: [ 'ps::install' ]
  when: ansible_os_family == "RedHat"

- name: Debian Specific Install
  include_tasks: install-Debian.yml
  tags: [ 'ps::install' ]
  when: ansible_os_family == "Debian"

- name: install bundle
  package:
    name: "{{ perfsonar_bundle }}"
    state: latest
  tags: [ 'ps::install' ]

- name: perfsonar-toolkit optional software
  include_tasks: toolkit.yml
  tags: [ 'ps::install' ]
  when: perfsonar_bundle == "perfsonar-toolkit"

- name: Install perfSONAR optional packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ perfsonar_optional_packages }}"
  tags: [ 'ps::install' ]
  when: perfsonar_bundle == "perfsonar-testpoint"

- name: add ntpservers
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ item }}"
  with_items: "{{ perfsonar_ntpservers }}"
  tags: [ 'ps::config' ]
  when: perfsonar_ntpservers is defined and perfsonar_ntpservers != none
  notify:
    - restart ntp

- name: perfsonar_interface config
  command: /usr/lib/perfsonar/scripts/mod_interface_route --command add --device "{{ item['interface_name'] }}" --ipv4_gateway "{{ item['interface_gateway_ipv4'] }}"
  with_items: "{{ perfsonar_interfaces }}"
  tags: [ 'ps::config' ]
  when: perfsonar_interfaces is defined and perfsonar_interfaces != none

- name: troubleshoot pscheduler
  command: pscheduler troubleshoot "{{ item }}"
  with_items: "{{ perfsonar_troubleshoot }}"
  tags: [ 'ps::install' ]
  when: perfsonar_troubleshoot is defined and perfsonar_troubleshoot != none
