---
# ps-extra.yml
#

### NTP
- name: download perfSONAR ntp package
  package:
    name: perfsonar-toolkit-ntp
    state: latest
  when: perfsonar_toolkit_ntp is defined and perfsonar_toolkit_ntp == true

- name: execute perfSONAR ntp package
  command: /usr/lib/perfsonar/scripts/configure_ntpd new
  when: perfsonar_toolkit_ntp is defined and perfsonar_toolkit_ntp == true
  notify:
    - restart ntp

### System Tuning
- name: download perfSONAR sysctl package
  package:
    name: perfsonar-toolkit-sysctl
    state: latest
  when: perfsonar_toolkit_configure_sysctl is defined and
        perfsonar_toolkit_configure_sysctl == true

- name: execute sysctl package
  command: /usr/lib/perfsonar/scripts/configure_sysctl
  when: perfsonar_toolkit_configure_sysctl is defined and
        perfsonar_toolkit_configure_sysctl == true

### Firewall
- name: download perfSONAR security package
  package:
    name: perfsonar-toolkit-security
    state: latest
  when: perfsonar_toolkit_security is defined and
        perfsonar_toolkit_security == true

- name: execute perfSONAR security script
  command: /usr/lib/perfsonar/scripts/configure_firewall install
  when: perfsonar_toolkit_security is defined and
        perfsonar_toolkit_security == true

### Autoupdate RedHat
- name: perfsonar yum autoupdate
  systemd:
    name: yum-cron
    state: started
    enabled: yes
  when: perfsonar_autoupdate is defined and perfsonar_autoupdate == true and
        ansible_os_family == "RedHat"

### Autoupdate Debian
- name: download perfSONAR unattended-upgrades package
  package:
    name: unattended-upgrades
    state: latest
  when: perfsonar_autoupdate is defined and perfsonar_autoupdate == true and
        ansible_os_family == "Debian"

- name: execute perfSONAR unattended-upgrades package
  command: /usr/lib/perfsonar/scripts/system_environment/enable_auto_updates new
  when: perfsonar_autoupdate is defined and perfsonar_autoupdate == true and
        ansible_os_family == "Debian"

### Servicewatcher
- name: download perfSONAR service_watcher
  package:
    name: perfsonar-toolkit-servicewatcher
    state: latest
  when: perfsonar_toolkit_service_watcher is defined and
        perfsonar_toolkit_service_watcher == true

- name: execute perfSONAR service_watcher script
  command: /usr/lib/perfsonar/scripts/service_watcher
  when: perfsonar_toolkit_service_watcher is defined and
        perfsonar_toolkit_service_watcher == true
