---
# perfsonar-testpoint.yml
#

- name: Install perfSONAR testpoint optional packages
  package:
    name: "{{ perfsonar_packages }}"
    state: present
  with_items: "{{ perfsonar_optional_packages }}"
  loop_control:
    loop_var: perfsonar_packages
